#!/usr/bin/env node

/**
 * @description Commit message checker.
 * @author Andrii Lytovchenko <andr.lyt.dev@gmail.com>
 * @license MIT
 */

const fs = require('fs');

const conv = [
  'feat',
  'fix',
  'chore',
  'refactor',
  'perf',
  'revert',
  'style',
  'release'
];

const message = fs.readFileSync(process.argv[2], 'utf8');
const isValid = conv.includes(message.split(':')[0]);

if(!isValid) {
   console.log('Commit message is not valid.');
   process.exit(1);
}
