#!/usr/bin/env bash

# description: pre-commit hook
# author Andrii Lytovchenko <andr.lyt.dev@gmail.com>
# license: MIT

set -e

npm i --package-lock-only
npm run format
npm run lint
npm run types
npm run spell
npm run svc
git add .
